### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by kidpollo** [Provisdom/spectomic#1]
I was going through the readme and I found something confusing. It might be a typo or something I 
am not quite getting. It would make sense to me if the first outlined item in my image below is more like `(s/def ::order (s/keys :req [:entity/id :order/name]))` 

I have not run this myself to verify. When I have time later I'll try.

![spectomic generate datomic or datascript schema from your clojure script specs 2017-07-22 22-27-18](https://user-images.githubusercontent.com/8182/28496901-5310fa1c-6f2d-11e7-9e4e-1efdeffdbaca.png)

**Comment by kennyjwilli** [comment]
Good catch! Just updated the README. Thanks!
