### ISSUE TITLE
Add syntax checking

### ISSUE THREAD

**Issue by sparkofreason** [Provisdom/spectomic#2]
When including schema attributes in the form `[::spec {db/...}]`, should check that the vector has only two elements, first is a spec, second is a map, etc.

**Comment by kennyjwilli** [comment]
If you enable instrumentation that error should be caught. The function is spec'ed [here](https://github.com/Provisdom/spectomic/blob/master/src/provisdom/spectomic/core.cljc#L91-L96).

**Comment by sparkofreason** [comment]
Not sure instrumentation is strong enough, because it's a silent failure.

**Comment by kennyjwilli** [comment]
It's only a silent failure if you don't enable instrumentation. It's not clear yet what the recommended best practice is for enabling instrumentation. I think this PR makes sense for the time being.
